"""Data models and schemas for the multi-tier Model Routing subsystem."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4
from pydantic import BaseModel, Field


class MessageRole(str, Enum):
    """Dialogue role types."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ChatMessage(BaseModel):
    """Individual message turn in the dialogue context."""
    role: MessageRole
    content: str
    name: str | None = None
    tool_call_id: str | None = None


class ToolCallDefinition(BaseModel):
    """Specification of a tool call generated by a model."""
    call_id: str = Field(default_factory=lambda: str(uuid4()))
    tool_name: str
    arguments: dict[str, Any]


class ModelRequest(BaseModel):
    """Standardized model inference request container."""
    request_id: UUID = Field(default_factory=uuid4)
    messages: list[ChatMessage]
    tier: str = "fast"
    temperature: float = 0.2
    max_tokens: int = 2048
    tools: list[dict[str, Any]] = Field(default_factory=list)
    stop_sequences: list[str] = Field(default_factory=list)


class ModelResponse(BaseModel):
    """Standardized model inference response container."""
    response_id: UUID = Field(default_factory=uuid4)
    model_name: str
    provider_name: str
    content: str = ""
    tool_calls: list[ToolCallDefinition] = Field(default_factory=list)
    finish_reason: str = "stop"
    prompt_tokens: int = 0
    completion_tokens: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
