"""JARVIS External Services Integration Package (Phase 9)."""

from services.base import (
    BaseCredentialProvider,
    BaseServiceAdapter,
    InMemoryCredentialProvider,
)
from services.connectors import (
    BaseHermeticConnector,
    ConnectorSimulationConfig,
    GitHubConnector,
    GmailConnector,
    GoogleCalendarConnector,
    GoogleDriveConnector,
    ServiceOutageError,
    ServiceRateLimitError,
    ServiceTimeoutError,
    SlackConnector,
)
from services.credentials import (
    ApiTokenCredentials,
    BaseCredential,
    BaseSecureStorage,
    BotTokenCredentials,
    CredentialType,
    GenericServiceCredentials,
    GitHubAuthAdapter,
    GmailAuthAdapter,
    GoogleCalendarAuthAdapter,
    GoogleDriveAuthAdapter,
    InMemorySecureStorage,
    KeychainSecureStorage,
    OAuth2Credentials,
    OAuth2LifecycleManager,
    OAuthError,
    OAuthRefreshError,
    OAuthState,
    OAuthStateError,
    SecureCredentialManager,
    SecureStorageError,
    SecureStorageUnavailableError,
    SlackAuthAdapter,
)
from services.mock_service import MockMessagingServiceAdapter
from services.models import (
    DuplicateServiceError,
    ServiceAuthenticationError,
    ServiceCapability,
    ServiceDisabledError,
    ServiceError,
    ServiceMetadata,
    ServiceNotFoundError,
    ServiceRequest,
    ServiceResponse,
    ServiceStatus,
    UndeclaredCapabilityError,
)
from services.permissions import ServicePermissionBridge
from services.registry import ServiceRegistry
from services.tool_bridge import ServiceTool, register_service_tools

__all__ = [
    "ApiTokenCredentials",
    "BaseCredential",
    "BaseCredentialProvider",
    "BaseHermeticConnector",
    "BaseSecureStorage",
    "BaseServiceAdapter",
    "BotTokenCredentials",
    "ConnectorSimulationConfig",
    "CredentialType",
    "DuplicateServiceError",
    "GenericServiceCredentials",
    "GitHubAuthAdapter",
    "GitHubConnector",
    "GmailAuthAdapter",
    "GmailConnector",
    "GoogleCalendarAuthAdapter",
    "GoogleCalendarConnector",
    "GoogleDriveAuthAdapter",
    "GoogleDriveConnector",
    "InMemoryCredentialProvider",
    "InMemorySecureStorage",
    "KeychainSecureStorage",
    "MockMessagingServiceAdapter",
    "OAuth2Credentials",
    "OAuth2LifecycleManager",
    "OAuthError",
    "OAuthRefreshError",
    "OAuthState",
    "OAuthStateError",
    "SecureCredentialManager",
    "SecureStorageError",
    "SecureStorageUnavailableError",
    "ServiceAuthenticationError",
    "ServiceCapability",
    "ServiceDisabledError",
    "ServiceError",
    "ServiceMetadata",
    "ServiceNotFoundError",
    "ServiceOutageError",
    "ServicePermissionBridge",
    "ServiceRateLimitError",
    "ServiceRegistry",
    "ServiceRequest",
    "ServiceResponse",
    "ServiceStatus",
    "ServiceTimeoutError",
    "ServiceTool",
    "SlackAuthAdapter",
    "SlackConnector",
    "UndeclaredCapabilityError",
    "register_service_tools",
]
